"""
BSA 2023 §63(4) certificate PDF generator.

Auto-generates a forensic certificate modeled on the Bharatiya Sakshya
Adhiniyam 2023 §63(4) requirements. Uses fpdf2 for PDF generation.

NOTE: Demo document for hackathon judges — not legally reviewed.
"""
from datetime import datetime
from typing import Dict, List, Optional

from fpdf import FPDF


def _sanitize(text: str) -> str:
    """Replace Unicode characters with ASCII equivalents for PDF compatibility."""
    if not isinstance(text, str):
        return str(text)
    return (text
        .replace("\u2014", "--")   # em dash
        .replace("\u2013", "-")    # en dash
        .replace("\u2018", "'")    # left single quote
        .replace("\u2019", "'")    # right single quote
        .replace("\u201c", '"')    # left double quote
        .replace("\u201d", '"')    # right double quote
        .replace("\u2022", "*")    # bullet
        .replace("\u2026", "...")  # ellipsis
        .replace("\u00a0", " ")    # non-breaking space
    )


class BSACertificatePDF(FPDF):
    """Custom PDF class for BSA §63(4) certificates."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "CERTIFICATE UNDER SECTION 63(4)", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "I", 10)
        self.cell(0, 6, "Bharatiya Sakshya Adhiniyam, 2023", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 5, f"Generated by MailShieldAI | {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(240, 240, 250)
        self.cell(0, 8, f"  {_sanitize(title)}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def field(self, label: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.cell(55, 6, _sanitize(label) + ":")
        self.set_font("Helvetica", "", 9)
        self.multi_cell(0, 6, _sanitize(value), new_x="LMARGIN", new_y="NEXT")


def generate_bsa_certificate(
    case_id: str,
    custodian_name: str = "System Administrator",
    custodian_designation: str = "MailShieldAI Platform",
    artifacts: Optional[List[Dict]] = None,
    verdict_summary: Optional[str] = None,
    timestamp: Optional[datetime] = None,
) -> bytes:
    """
    Generate a BSA §63(4) certificate PDF.

    Returns PDF file as bytes.
    """
    pdf = BSACertificatePDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    timestamp = timestamp or datetime.utcnow()

    # ── Part A — Custodian Details ──────────────────────
    pdf.section_title("PART A — Identification & Custodian Details")

    pdf.field("Case Reference", case_id)
    pdf.field("Date of Generation", timestamp.strftime("%d %B %Y, %H:%M:%S UTC"))
    pdf.field("Name of Custodian", custodian_name)
    pdf.field("Designation", custodian_designation)
    pdf.field("Organization", "MailShieldAI — AI-Powered Email Threat Detection Platform")
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, _sanitize("Description of Computer System:"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, _sanitize(
        "The electronic record was produced by the MailShieldAI platform, "
        "an automated email threat detection, geolocation, and forensic intelligence system. "
        "The platform ingests email data, performs AI-based threat analysis, reconstructs "
        "geo-forensic hop chains, and produces tamper-evident evidence chains with SHA-256 "
        "hashing and Merkle tree verification."
    ), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Evidence Artifacts & Hash Values ────────────────
    pdf.section_title(_sanitize("Evidence Artifacts & Hash Values (SHA-256)"))

    if artifacts:
        pdf.set_font("Helvetica", "B", 8)
        col_widths = [10, 55, 95, 30]
        headers = ["#", "Artifact Name", "SHA-256 Hash", "Type"]
        for w, h in zip(col_widths, headers):
            pdf.cell(w, 6, _sanitize(h), border=1)
        pdf.ln()

        pdf.set_font("Courier", "", 7)
        for i, artifact in enumerate(artifacts, 1):
            pdf.cell(col_widths[0], 5, str(i), border=1)
            pdf.set_font("Helvetica", "", 7)
            pdf.cell(col_widths[1], 5, _sanitize(artifact.get("name", "")[:35]), border=1)
            pdf.set_font("Courier", "", 6)
            pdf.cell(col_widths[2], 5, _sanitize(artifact.get("sha256", "")[:64]), border=1)
            pdf.set_font("Helvetica", "", 7)
            pdf.cell(col_widths[3], 5, _sanitize(artifact.get("type", "")), border=1)
            pdf.ln()
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, _sanitize("No artifacts recorded for this case."), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # ── AI Verdict Summary ──────────────────────────────
    if verdict_summary:
        pdf.section_title(_sanitize("AI Analysis Summary"))
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _sanitize(verdict_summary), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # ── Part B — Expert Certification ───────────────────
    pdf.section_title(_sanitize("PART B — Certification"))

    certifications = [
        "I hereby certify that the electronic record(s) described above were produced "
        "by the computer system during the period over which the system was used regularly "
        "to store or process information for the purposes of any activities regularly "
        "carried on over that period by the person having lawful control over the use of "
        "the computer.",

        "The information contained in the electronic record was regularly fed into the "
        "computer in the ordinary course of the said activities.",

        "Throughout the material part of the said period, the computer was operating "
        "properly or, if not, that any respect in which it was not operating properly or "
        "was out of operation during that part of that period was not such as to affect "
        "the electronic record or the accuracy of its contents.",

        "The information contained in the electronic record reproduces or is derived "
        "from such information fed into the computer in the ordinary course of the "
        "said activities.",
    ]

    pdf.set_font("Helvetica", "", 9)
    for i, cert in enumerate(certifications, 1):
        pdf.multi_cell(0, 5, _sanitize(f"({i}) {cert}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    pdf.ln(4)

    # ── Signature block ─────────────────────────────────
    pdf.line(10, pdf.get_y(), 100, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 5, f"Name: {custodian_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Designation: {custodian_designation}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Date: {timestamp.strftime('%d/%m/%Y')}", new_x="LMARGIN", new_y="NEXT")

    return pdf.output()


def generate_forensic_report(
    case_id: str,
    case_data: Dict,
    geo_data: Dict,
    verdict_data: Dict,
    evidence_data: Dict,
) -> bytes:
    """Generate a full forensic case report PDF."""
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 12, _sanitize("FORENSIC CASE REPORT"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, _sanitize(f"Case ID: {case_id}"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _sanitize(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Case Summary
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, _sanitize("1. Case Summary"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)

    summary_fields = [
        ("Subject", case_data.get("subject", "N/A")),
        ("Sender", case_data.get("sender", "N/A")),
        ("Recipient", case_data.get("recipient", "N/A")),
        ("Date", case_data.get("date_sent", "N/A")),
        ("Risk Score", str(verdict_data.get("risk_score", "N/A"))),
        ("Verdict", verdict_data.get("verdict", "N/A")),
    ]
    for label, value in summary_fields:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(35, 6, _sanitize(f"{label}:"))
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 6, _sanitize(str(value)[:80]), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # AI Analysis
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, _sanitize("2. AI Analysis & Reasoning"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)

    shap_data = verdict_data.get("shap_explanation", [])
    if shap_data:
        for item in shap_data[:7]:
            field = item.get("field", "")
            value = item.get("value", "")
            contrib = item.get("contribution", 0)
            pdf.cell(0, 5, _sanitize(f"* {field}: {value} (contribution: {contrib:+.2%})"), new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(0, 5, _sanitize("No SHAP explanation available."), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # Geo-Forensic Analysis
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, _sanitize("3. Geo-Forensic Hop Chain"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)

    hops = geo_data.get("hops", [])
    for hop in hops:
        flags = []
        if hop.get("is_forged"): flags.append("FORGED")
        if hop.get("is_tor_exit"): flags.append("TOR")
        if hop.get("is_vpn"): flags.append("VPN")
        flag_str = _sanitize(f" [{', '.join(flags)}]") if flags else ""

        pdf.cell(0, 5,
            _sanitize(f"Hop {hop.get('hop_index', '?')}: {hop.get('ip_address', 'N/A')} "
            f"({hop.get('country', '?')}, {hop.get('city', '?')}) "
            f"ASN: {hop.get('asn', 'N/A')}{flag_str}"),
            new_x="LMARGIN", new_y="NEXT",
        )

    pdf.ln(4)

    # Evidence Chain
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, _sanitize("4. Evidence Chain Verification"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)

    pdf.cell(0, 5, _sanitize(f"Merkle Root: {evidence_data.get('merkle_root', 'N/A')}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, _sanitize(f"Chain Verified: {evidence_data.get('chain_verified', 'N/A')}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, _sanitize(f"Ledger Entries: {evidence_data.get('ledger_entries', 0)}"), new_x="LMARGIN", new_y="NEXT")

    return pdf.output()
